config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  scope module: :public do
    resources :items, only:[:index, :show]
    get '/about' => 'homes#about'
    resources :customers, only:[:show, :edit, :update]
    get 'unsubsceibe' => 'customers#unsubsceibe'
    patch 'withdraw' => 'customers#withdraw'
    resources :cart_items, only:[:index, :update, :destroy, :create]
    delete 'all_destroy' => 'cart_items#all_destroy'
    resources :orders, only:[:new, :create, :index, :show]
    post 'log' => 'orders#log'
    get 'thanks' => 'orders#thanks'
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :sessions, only:[:new, :create, :destroy]
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :orders_details, only:[:update]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer


  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable






    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  def subtotal
    item.price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    def name
      [first_name, last_name].join(' ')
    end
  has_many :addresses
  has_many :cart_items
  has_many :orders
  # enum is_active: { "有効": true, "退会": false }


  def active_for_authentication?
    super && (self.is_active != false)
  end


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/home.rb
class Home < ApplicationRecord
  
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :order_details
  enum is_active_method: { "販売中": true, "販売停止中": false }
  has_many :cart_items
  def price_add_tax
    tax=1.1
    (self.price*tax).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_active: { waiting_for_deposit: 0, payment_confirmation: 1, production: 2, ready_to_ship: 3, sent: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { cannot_be_manufactured: 0, waiting_for_production: 1, production: 2, production_completed: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @customer = @order.customer
  end

  def update
    @order = Order.find(params[:id])
    @order.update(orders_params)
    redirect_to admin_root_path
  end

  private
  def orders_params
    params.require(:order).permit(:name, :addresses, :payment_method, :postage, :order_active, :billing_amount, :postal_code)
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/public_homes_helper.rb
module PublicHomesHelper
end

app/helpers/public_items_helper.rb
module PublicItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/orders/show.html.erb
<main>
  <div class="container px-5 px-sm-0 mx-auto">
    <div class="row">
      <h4 class="bg-secondary d-inline px2">注文履歴詳細</h4>
      <div class="col">
        <h5>購入者</h5>
        <p><%= @customer.first_name + @customer.last_name %></p>
        <h5>注文日</h5>
        <p><%= @order.created_at %></p>
        <h5>配送先</h5>
        <p><%= @order.addresses %></p>
        <h5>支払方法</h5>
        <p><%= @order.payment_method %></p>
        <h5>注文ステータス</h5>
        <%= form_with model:@order, url:admin_order_path, method: :patch, local:true do |f| %>
        <p>
          <%= f.select :order_active, Order.order_actives_i18n.invert %>
          <%= f.submit "更新", class:"btn btn-success" %>
        </p>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">商品名</th>
              <th scope="col">単価（税込）</th>
              <th scope="col">数量</th>
              <th scope="col">小計</th>
              <th scope="col">製作ステータス</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <% @order.order_details.each do |d| %>
            <tr>
              <td><%= d.item.name %></td>
              <td><%= d.item.price_add_tax %></td>
              <td><%= d.amount %></td>
              <td><%= d.price * d.amount %></td>
              <%= form_with model: d, url: admin_orders_detail_path, method: :patch, local: true do |f| %>
              <td><%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %></td>
              <td><%= f.submit "更新", class:"btn btn-success" %></td>
              <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col">
        <h5>商品合計</h5>
        <p><%= @order.billing_amount - @order.postage %></p>
        <h5>送料</h5>
        <p><%= @order.postage %></p>
        <h5>請求額合計</h5>
        <p><%= @order.billing_amount %></p>
      </div>
    </div>
  </div>
</main>