config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  scope module: :public do
    resources :items, only:[:index, :show]
    get '/about' => 'homes#about'
    resources :customers, only:[:show, :edit, :update]
    get 'unsubsceibe' => 'customers#unsubsceibe'
    patch 'withdraw' => 'customers#withdraw'
    resources :cart_items, only:[:index, :update, :destroy, :create]
    delete 'all_destroy' => 'cart_items#all_destroy'
    resources :orders, only:[:new, :create, :index, :show]
    post 'log' => 'orders#log'
    get 'thanks' => 'orders#thanks'
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :sessions, only:[:new, :create, :destroy]
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :orders_details, only:[:update]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer


  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable






    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  def subtotal
    item.price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    def name
      [first_name, last_name].join(' ')
    end
  has_many :addresses
  has_many :cart_items
  has_many :orders
  # enum is_active: { "有効": true, "退会": false }


  def active_for_authentication?
    super && (self.is_active != false)
  end


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/home.rb
class Home < ApplicationRecord
  
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :order_details
  enum is_active_method: { "販売中": true, "販売停止中": false }
  has_many :cart_items
  def price_add_tax
    tax=1.1
    (self.price*tax).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_active: { waiting_for_deposit: 0, payment_confirmation: 1, production: 2, ready_to_ship: 3, sent: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { cannot_be_manufactured: 0, waiting_for_production: 1, production: 2, production_completed: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <script src="https://kit.fontawesome.com/09f2426f63.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
  <header>
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
     <div class="container">
         <a class="navbar-brand">
             <button type="button" class="btn btn-outline-dark" >LOGO</button>
         </a>
         <ul class="nav justify-content-end">
          <% if admin_signed_in? %>
           <li class="nav-item">
             <%= link_to "商品一覧", admin_items_path, class:"btn btn-outline-dark" %>
           </li>
           <li class="nav-item">
             <%= link_to "会員一覧", admin_customers_path, class:"btn btn-outline-dark" %>
           </li>
           <li class="nav-item">
             <%= link_to "注文履歴一覧", admin_root_path, class:"btn btn-outline-dark" %>
           </li>
           <li class="nav-item">
             <%= link_to "ジャンル一覧",  admin_genres_path, class:"btn btn-outline-dark" %>
           </li>
           <li class="nav-item">
             <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"btn btn-outline-dark" %>
           </li>
          <% elsif customer_signed_in? %>
           <h5>ようこそ、<%= current_customer.first_name %>さん！</h5>
           <li class="nav-item">
             <%= link_to "マイページ", customer_path(current_customer), class:"btn btn-outline-dark" %>
           </li>
           <li class="nav-item">
             <%= link_to "商品一覧", items_path, class:"btn btn-outline-dark" %>
           </li>
           <li class="nav-item">
             <%= link_to "カート", cart_items_path, class:"btn btn-outline-dark" %>
           </li>
           <li class="nav-item">
             <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"btn btn-outline-dark" %>
           </li>
          <% else %>
           <li class="nav-item">
             <%= link_to "About", about_path, class:"btn btn-outline-dark" %>
           </li>
           <li class="nav-item">
             <%= link_to "商品一覧", items_path, class:"btn btn-outline-dark" %>
           </li>
           <li class="nav-item">
             <%= link_to "新規登録", new_customer_registration_path, class:"btn btn-outline-dark" %>
           </li>
           <li class="nav-item">
             <%= link_to "ログイン", new_customer_session_path, class:"btn btn-outline-dark" %>
           </li>
          <% end %>
         </ul>
     </div>
   </nav>
  </header>
  <%= yield %>
  </body>
</html>